In [172]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [173]:
dataFrame= pd.read_csv("alzheimer.csv")

In [174]:
dataFrame.head()

Group M/F  Age  EDUC  SES  MMSE  CDR  eTIV   nWBV    ASF
0  Nondemented   M   87    14  2.0  27.0  0.0  1987  0.696  0.883
1  Nondemented   M   88    14  2.0  30.0  0.0  2004  0.681  0.876
2     Demented   M   75    12  NaN  23.0  0.5  1678  0.736  1.046
3     Demented   M   76    12  NaN  28.0  0.5  1738  0.713  1.010
4     Demented   M   80    12  NaN  22.0  0.5  1698  0.701  1.034

In [175]:
dataFrame.describe()

Age        EDUC         SES        MMSE         CDR  \
count  373.000000  373.000000  354.000000  371.000000  373.000000   
mean    77.013405   14.597855    2.460452   27.342318    0.290885   
std      7.640957    2.876339    1.134005    3.683244    0.374557   
min     60.000000    6.000000    1.000000    4.000000    0.000000   
25%     71.000000   12.000000    2.000000   27.000000    0.000000   
50%     77.000000   15.000000    2.000000   29.000000    0.000000   
75%     82.000000   16.000000    3.000000   30.000000    0.500000   
max     98.000000   23.000000    5.000000   30.000000    2.000000   

              eTIV        nWBV         ASF  
count   373.000000  373.000000  373.000000  
mean   1488.128686    0.729568    1.195461  
std     176.139286    0.037135    0.138092  
min    1106.000000    0.644000    0.876000  
25%    1357.000000    0.700000    1.099000  
50%    1470.000000    0.729000    1.194000  
75%    1597.000000    0.756000    1.293000  
max    2004.000000    0.837000    1.587000

In [176]:
dataFrame.isnull().sum()

Group     0
M/F       0
Age       0
EDUC      0
SES      19
MMSE      2
CDR       0
eTIV      0
nWBV      0
ASF       0
dtype: int64

In [177]:
dataFrame

Group M/F  Age  EDUC  SES  MMSE  CDR  eTIV   nWBV    ASF
0    Nondemented   M   87    14  2.0  27.0  0.0  1987  0.696  0.883
1    Nondemented   M   88    14  2.0  30.0  0.0  2004  0.681  0.876
2       Demented   M   75    12  NaN  23.0  0.5  1678  0.736  1.046
3       Demented   M   76    12  NaN  28.0  0.5  1738  0.713  1.010
4       Demented   M   80    12  NaN  22.0  0.5  1698  0.701  1.034
..           ...  ..  ...   ...  ...   ...  ...   ...    ...    ...
368     Demented   M   82    16  1.0  28.0  0.5  1693  0.694  1.037
369     Demented   M   86    16  1.0  26.0  0.5  1688  0.675  1.040
370  Nondemented   F   61    13  2.0  30.0  0.0  1319  0.801  1.331
371  Nondemented   F   63    13  2.0  30.0  0.0  1327  0.796  1.323
372  Nondemented   F   65    13  2.0  30.0  0.0  1333  0.801  1.317

[373 rows x 10 columns]

In [178]:
imputer = SimpleImputer(missing_values = np.nan,strategy='mean')

In [179]:
meanValue= dataFrame.iloc[:,4:6].values

In [180]:
meanValue

array([[ 2., 27.],
       [ 2., 30.],
       [nan, 23.],
       [nan, 28.],
       [nan, 22.],
       [ 3., 28.],
       [ 3., 27.],
       [ 4., 28.],
       [ 4., 29.],
       [ 4., 30.],
       [nan, 28.],
       [nan, 27.],
       [nan, 27.],
       [ 2., 30.],
       [ 2., 29.],
       [ 2., 27.],
       [ 2., 24.],
       [ 3., 30.],
       [ 3., 29.],
       [ 2., 29.],
       [ 2., 29.],
       [ 2., 29.],
       [ 4., 30.],
       [ 4., 30.],
       [ 4., 29.],
       [ 3., 21.],
       [ 3., 16.],
       [ 4., 25.],
       [ 4., 23.],
       [ 3., 29.],
       [ 3., 27.],
       [ 3., 30.],
       [ 3., 27.],
       [ 1., 30.],
       [ 1., 29.],
       [ 1., 27.],
       [ 1., 29.],
       [ 1., 28.],
       [ 1., 26.],
       [ 1., 26.],
       [ 1., 25.],
       [ 3., 30.],
       [ 3., 29.],
       [ 4., 21.],
       [ 4., 21.],
       [ 3., 27.],
       [ 3., 27.],
       [ 3., 29.],
       [ 3., 30.],
       [ 3., 30.],
       [ 3., 30.],
       [ 2., 22.],
       [ 2.,

In [181]:
imputer = imputer.fit(meanValue)

In [182]:
meanValue

array([[ 2., 27.],
       [ 2., 30.],
       [nan, 23.],
       [nan, 28.],
       [nan, 22.],
       [ 3., 28.],
       [ 3., 27.],
       [ 4., 28.],
       [ 4., 29.],
       [ 4., 30.],
       [nan, 28.],
       [nan, 27.],
       [nan, 27.],
       [ 2., 30.],
       [ 2., 29.],
       [ 2., 27.],
       [ 2., 24.],
       [ 3., 30.],
       [ 3., 29.],
       [ 2., 29.],
       [ 2., 29.],
       [ 2., 29.],
       [ 4., 30.],
       [ 4., 30.],
       [ 4., 29.],
       [ 3., 21.],
       [ 3., 16.],
       [ 4., 25.],
       [ 4., 23.],
       [ 3., 29.],
       [ 3., 27.],
       [ 3., 30.],
       [ 3., 27.],
       [ 1., 30.],
       [ 1., 29.],
       [ 1., 27.],
       [ 1., 29.],
       [ 1., 28.],
       [ 1., 26.],
       [ 1., 26.],
       [ 1., 25.],
       [ 3., 30.],
       [ 3., 29.],
       [ 4., 21.],
       [ 4., 21.],
       [ 3., 27.],
       [ 3., 27.],
       [ 3., 29.],
       [ 3., 30.],
       [ 3., 30.],
       [ 3., 30.],
       [ 2., 22.],
       [ 2.,

In [183]:
meanValue= imputer.transform(meanValue)

In [184]:
meanValue

array([[ 2.        , 27.        ],
       [ 2.        , 30.        ],
       [ 2.46045198, 23.        ],
       [ 2.46045198, 28.        ],
       [ 2.46045198, 22.        ],
       [ 3.        , 28.        ],
       [ 3.        , 27.        ],
       [ 4.        , 28.        ],
       [ 4.        , 29.        ],
       [ 4.        , 30.        ],
       [ 2.46045198, 28.        ],
       [ 2.46045198, 27.        ],
       [ 2.46045198, 27.        ],
       [ 2.        , 30.        ],
       [ 2.        , 29.        ],
       [ 2.        , 27.        ],
       [ 2.        , 24.        ],
       [ 3.        , 30.        ],
       [ 3.        , 29.        ],
       [ 2.        , 29.        ],
       [ 2.        , 29.        ],
       [ 2.        , 29.        ],
       [ 4.        , 30.        ],
       [ 4.        , 30.        ],
       [ 4.        , 29.        ],
       [ 3.        , 21.        ],
       [ 3.        , 16.        ],
       [ 4.        , 25.        ],
       [ 4.        ,

In [185]:
dataFrame["SES"] = meanValue[:,0]

In [186]:
dataFrame["MMSE"] = meanValue[:,1]

In [187]:
dataFrame

Group M/F  Age  EDUC       SES  MMSE  CDR  eTIV   nWBV    ASF
0    Nondemented   M   87    14  2.000000  27.0  0.0  1987  0.696  0.883
1    Nondemented   M   88    14  2.000000  30.0  0.0  2004  0.681  0.876
2       Demented   M   75    12  2.460452  23.0  0.5  1678  0.736  1.046
3       Demented   M   76    12  2.460452  28.0  0.5  1738  0.713  1.010
4       Demented   M   80    12  2.460452  22.0  0.5  1698  0.701  1.034
..           ...  ..  ...   ...       ...   ...  ...   ...    ...    ...
368     Demented   M   82    16  1.000000  28.0  0.5  1693  0.694  1.037
369     Demented   M   86    16  1.000000  26.0  0.5  1688  0.675  1.040
370  Nondemented   F   61    13  2.000000  30.0  0.0  1319  0.801  1.331
371  Nondemented   F   63    13  2.000000  30.0  0.0  1327  0.796  1.323
372  Nondemented   F   65    13  2.000000  30.0  0.0  1333  0.801  1.317

[373 rows x 10 columns]

In [188]:
teshis= dataFrame.iloc[:,0:1].values

In [189]:
teshis

array([['Nondemented'],
       ['Nondemented'],
       ['Demented'],
       ['Demented'],
       ['Demented'],
       ['Nondemented'],
       ['Nondemented'],
       ['Nondemented'],
       ['Nondemented'],
       ['Nondemented'],
       ['Demented'],
       ['Demented'],
       ['Demented'],
       ['Nondemented'],
       ['Nondemented'],
       ['Demented'],
       ['Demented'],
       ['Demented'],
       ['Demented'],
       ['Nondemented'],
       ['Nondemented'],
       ['Nondemented'],
       ['Nondemented'],
       ['Nondemented'],
       ['Nondemented'],
       ['Demented'],
       ['Demented'],
       ['Demented'],
       ['Demented'],
       ['Nondemented'],
       ['Nondemented'],
       ['Nondemented'],
       ['Nondemented'],
       ['Converted'],
       ['Converted'],
       ['Converted'],
       ['Converted'],
       ['Converted'],
       ['Converted'],
       ['Demented'],
       ['Demented'],
       ['Nondemented'],
       ['Nondemented'],
       ['Demented'],
       

In [190]:
le= preprocessing.LabelEncoder()

In [191]:
teshis=le.fit_transform(teshis)

C:\Users\dilar\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [192]:
teshis

array([2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 1,
       1, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 0, 0, 0, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 2, 2, 1, 1,
       1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       1, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 0, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 0, 0,
       0, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       2, 2, 2, 0, 0, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 0, 0, 0,
       0, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 1,

In [193]:
dataFrame["Group"]=teshis

In [194]:
dataFrame

Group M/F  Age  EDUC       SES  MMSE  CDR  eTIV   nWBV    ASF
0        2   M   87    14  2.000000  27.0  0.0  1987  0.696  0.883
1        2   M   88    14  2.000000  30.0  0.0  2004  0.681  0.876
2        1   M   75    12  2.460452  23.0  0.5  1678  0.736  1.046
3        1   M   76    12  2.460452  28.0  0.5  1738  0.713  1.010
4        1   M   80    12  2.460452  22.0  0.5  1698  0.701  1.034
..     ...  ..  ...   ...       ...   ...  ...   ...    ...    ...
368      1   M   82    16  1.000000  28.0  0.5  1693  0.694  1.037
369      1   M   86    16  1.000000  26.0  0.5  1688  0.675  1.040
370      2   F   61    13  2.000000  30.0  0.0  1319  0.801  1.331
371      2   F   63    13  2.000000  30.0  0.0  1327  0.796  1.323
372      2   F   65    13  2.000000  30.0  0.0  1333  0.801  1.317

[373 rows x 10 columns]

In [195]:
dataFrame.rename(columns={'M/F':'mf'},inplace=True)

In [196]:
nondemented=dataFrame[dataFrame.Group==2]

In [197]:
converted=dataFrame[dataFrame.Group==0]

In [198]:
demented=dataFrame[dataFrame.Group==1] 

In [199]:
cinsiyet= dataFrame.iloc[:,1:2].values

In [200]:
le= preprocessing.LabelEncoder()

In [201]:
cinsiyet= le.fit_transform(cinsiyet)

C:\Users\dilar\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [202]:
male=dataFrame[dataFrame.mf==1]
female=dataFrame[dataFrame.mf==0]

In [203]:
dataFrame.rename(columns={'mf':'M/F'},inplace=True)

In [204]:
dataFrame["M/F"]=cinsiyet

In [205]:
dataFrame

Group  M/F  Age  EDUC       SES  MMSE  CDR  eTIV   nWBV    ASF
0        2    1   87    14  2.000000  27.0  0.0  1987  0.696  0.883
1        2    1   88    14  2.000000  30.0  0.0  2004  0.681  0.876
2        1    1   75    12  2.460452  23.0  0.5  1678  0.736  1.046
3        1    1   76    12  2.460452  28.0  0.5  1738  0.713  1.010
4        1    1   80    12  2.460452  22.0  0.5  1698  0.701  1.034
..     ...  ...  ...   ...       ...   ...  ...   ...    ...    ...
368      1    1   82    16  1.000000  28.0  0.5  1693  0.694  1.037
369      1    1   86    16  1.000000  26.0  0.5  1688  0.675  1.040
370      2    0   61    13  2.000000  30.0  0.0  1319  0.801  1.331
371      2    0   63    13  2.000000  30.0  0.0  1327  0.796  1.323
372      2    0   65    13  2.000000  30.0  0.0  1333  0.801  1.317

[373 rows x 10 columns]

In [206]:
dataFrame.corr()

Group       M/F       Age      EDUC       SES      MMSE       CDR  \
Group  1.000000 -0.143918 -0.049267  0.100606  0.053290  0.339906 -0.572518   
M/F   -0.143918  1.000000 -0.037726  0.089279 -0.044525 -0.166521  0.202140   
Age   -0.049267 -0.037726  1.000000 -0.027886 -0.046665  0.055607 -0.026257   
EDUC   0.100606  0.089279 -0.027886  1.000000 -0.708680  0.194454 -0.153121   
SES    0.053290 -0.044525 -0.046665 -0.708680  1.000000 -0.146913  0.073393   
MMSE   0.339906 -0.166521  0.055607  0.194454 -0.146913  1.000000 -0.679837   
CDR   -0.572518  0.202140 -0.026257 -0.153121  0.073393 -0.679837  1.000000   
eTIV   0.056693  0.572549  0.042348  0.257015 -0.254271 -0.031789  0.022819   
nWBV   0.258093 -0.249618 -0.518359 -0.012200  0.089436  0.341857 -0.344819   
ASF   -0.042848 -0.561647 -0.035067 -0.241752  0.246673  0.039494 -0.029340   

           eTIV      nWBV       ASF  
Group  0.056693  0.258093 -0.042848  
M/F    0.572549 -0.249618 -0.561647  
Age    0.042348 -0.518359 -0.035067  
EDUC   0.257015 -0.012200 -0.241752  
SES   -0.254271  0.089436  0.246673  
MMSE  -0.031789  0.341857  0.039494  
CDR    0.022819 -0.344819 -0.029340  
eTIV   1.000000 -0.210122 -0.988877  
nWBV  -0.210122  1.000000  0.213476  
ASF   -0.988877  0.213476  1.000000

In [207]:
dataFrame

Group  M/F  Age  EDUC       SES  MMSE  CDR  eTIV   nWBV    ASF
0        2    1   87    14  2.000000  27.0  0.0  1987  0.696  0.883
1        2    1   88    14  2.000000  30.0  0.0  2004  0.681  0.876
2        1    1   75    12  2.460452  23.0  0.5  1678  0.736  1.046
3        1    1   76    12  2.460452  28.0  0.5  1738  0.713  1.010
4        1    1   80    12  2.460452  22.0  0.5  1698  0.701  1.034
..     ...  ...  ...   ...       ...   ...  ...   ...    ...    ...
368      1    1   82    16  1.000000  28.0  0.5  1693  0.694  1.037
369      1    1   86    16  1.000000  26.0  0.5  1688  0.675  1.040
370      2    0   61    13  2.000000  30.0  0.0  1319  0.801  1.331
371      2    0   63    13  2.000000  30.0  0.0  1327  0.796  1.323
372      2    0   65    13  2.000000  30.0  0.0  1333  0.801  1.317

[373 rows x 10 columns]

In [208]:
x=dataFrame.iloc[:,1:10].values #bağımlı değişken

In [209]:
y=dataFrame.iloc[:,0].values #bağımsız değişkenler

In [210]:
x

array([[1.000e+00, 8.700e+01, 1.400e+01, ..., 1.987e+03, 6.960e-01,
        8.830e-01],
       [1.000e+00, 8.800e+01, 1.400e+01, ..., 2.004e+03, 6.810e-01,
        8.760e-01],
       [1.000e+00, 7.500e+01, 1.200e+01, ..., 1.678e+03, 7.360e-01,
        1.046e+00],
       ...,
       [0.000e+00, 6.100e+01, 1.300e+01, ..., 1.319e+03, 8.010e-01,
        1.331e+00],
       [0.000e+00, 6.300e+01, 1.300e+01, ..., 1.327e+03, 7.960e-01,
        1.323e+00],
       [0.000e+00, 6.500e+01, 1.300e+01, ..., 1.333e+03, 8.010e-01,
        1.317e+00]])

In [211]:
y

array([2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 1,
       1, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 0, 0, 0, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 2, 2, 1, 1,
       1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       1, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 0, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 0, 0,
       0, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       2, 2, 2, 0, 0, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 0, 0, 0,
       0, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 1,

In [283]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.44,random_state=1)

In [284]:
sc=StandardScaler()

In [285]:
X_train=sc.fit_transform(x_train)

In [286]:
X_test=sc.transform(x_test)

In [287]:
logr= LogisticRegression(random_state=0)

In [288]:
logr.fit(X_train,y_train) #eğitilmiş model

LogisticRegression(random_state=0)

In [291]:
logr.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [292]:
y_pred=logr.predict(X_test)  #eğitilmiş metoda predict etmesini söylüyor

In [293]:
y_pred

array([2, 2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 0, 2, 1, 2, 2, 2,
       1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2,
       1, 1, 2, 1, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 1, 1, 2, 2, 1,
       1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 2, 1, 2,
       2, 1, 0, 1, 1, 1, 0, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1,
       2, 2, 2, 1, 2, 1, 1, 2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 2, 2, 2,
       1, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 1, 2,
       2, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1])

In [294]:
y_test

array([2, 0, 2, 2, 1, 0, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 0, 2, 1, 2, 2, 2,
       1, 0, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 0, 2, 2, 2,
       1, 1, 0, 1, 1, 2, 2, 1, 2, 0, 1, 2, 2, 1, 2, 2, 2, 1, 1, 2, 2, 1,
       1, 1, 2, 2, 1, 1, 2, 2, 0, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 2, 1, 2,
       2, 1, 0, 1, 1, 1, 0, 1, 2, 2, 2, 2, 2, 1, 2, 2, 0, 1, 2, 0, 1, 1,
       2, 2, 2, 1, 2, 1, 1, 2, 1, 2, 0, 1, 2, 2, 1, 1, 2, 2, 1, 2, 2, 2,
       1, 2, 2, 1, 2, 1, 2, 0, 2, 2, 2, 0, 2, 2, 1, 2, 2, 2, 2, 1, 1, 0,
       2, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1])

In [296]:
logr.score(X_test,y_test)

0.9212121212121213

In [297]:
from sklearn.metrics import confusion_matrix #confusion matrix classı import edildi

In [298]:
cm = confusion_matrix(y_test,y_pred) #confusion matrix objesi oluşturuldu

In [300]:
cm

array([[ 3,  4,  9],
       [ 0, 60,  0],
       [ 0,  0, 89]], dtype=int64)

In [301]:
from sklearn.metrics import confusion_matrix, classification_report

In [302]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       1.00      0.19      0.32        16\n           1       0.94      1.00      0.97        60\n           2       0.91      1.00      0.95        89\n\n    accuracy                           0.92       165\n   macro avg       0.95      0.73      0.75       165\nweighted avg       0.93      0.92      0.90       165\n'

In [303]:
##########

In [304]:
knn= KNeighborsClassifier(n_neighbors=5,metric='minkowski')

In [305]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [306]:
y_pred=knn.predict(X_test)

In [307]:
cm = confusion_matrix(y_test,y_pred)

In [308]:
cm

array([[ 4,  5,  7],
       [ 1, 59,  0],
       [ 2,  1, 86]], dtype=int64)

In [309]:
sayac=1
for k in range (1,100):
    knn_yeni= KNeighborsClassifier(n_neighbors=k)
    knn_yeni.fit(X_train,y_train)
    print(sayac,knn_yeni.score(X_test,y_test)*100)
    sayac+=1

1 86.06060606060606
2 78.78787878787878
3 89.0909090909091
4 88.48484848484848
5 90.30303030303031
6 91.51515151515152
7 92.12121212121212
8 90.9090909090909
9 90.30303030303031
10 89.6969696969697
11 90.30303030303031
12 89.6969696969697
13 89.0909090909091
14 87.87878787878788
15 89.0909090909091
16 88.48484848484848
17 87.87878787878788
18 87.87878787878788
19 87.27272727272727
20 87.27272727272727
21 88.48484848484848
22 86.66666666666667
23 86.66666666666667
24 87.27272727272727
25 87.27272727272727
26 87.27272727272727
27 87.27272727272727
28 86.66666666666667
29 87.27272727272727
30 87.87878787878788
31 87.87878787878788
32 87.87878787878788
33 87.27272727272727
34 87.27272727272727
35 87.87878787878788
36 87.27272727272727
37 87.27272727272727
38 86.66666666666667
39 86.66666666666667
40 87.27272727272727
41 87.87878787878788
42 87.87878787878788
43 87.87878787878788
44 87.87878787878788
45 87.27272727272727
46 87.27272727272727
47 87.27272727272727
48 87.27272727272727
49 86.6